ptz: true
# Internal configuration of the camera. It can instantly flip the camera head 180 degrees and continue to pan beyond its zero point
autoflip: false
# Internal configuration of the camera. It can automatically flip the image electronically 180 degrees, and continue to follow the person in the correct orientation, without delay.
eflip: false
#
use_only_zoom: true
min_zoom_value: 0
max_zoom_value: 19999
# Flag to invert received/sent pan and tilt values
invert_ptz: true
